# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZAl78PXdj2fsc96iOboLCZc4X_AWX38Q
"""

# Trabajo Final Aprendizaje de Maquinas_Daniel Lezcano_V1_Despliegue

import streamlit as st
import pandas as pd
import joblib
# ======================================================
# CONFIGURACIÓN
# ======================================================
st.set_page_config(
page_title="Predicción de Riesgo Académico",
page_icon="🎓",
layout="wide"
)
# ======================================================
# CARGA DEL MODELO
# ======================================================
modelo = joblib.load("modelo_final_saberpro_comprimido.pkl")
# ======================================================
# CABECERA
# ======================================================
st.title("🎓 Predicción de Riesgo de Bajo Desempeño")
st.markdown("""
### Proyecto Académico

**Maestría en Ciencia de Datos - Universidad Pontificia Bolivariana (UPB)**

Esta aplicación utiliza Machine Learning para estimar el riesgo de bajo desempeño
en razonamiento cuantitativo a partir de variables académicas y socioeconómicas.
""")
st.divider()
# ======================================================
# FORMULARIO
# ======================================================
st.subheader("Información del estudiante")
col1, col2 = st.columns(2)
with col1:
periodo = st.selectbox(
"Periodo",
["20183","20184","20194","20195","20203","20204","20212"]
)
modalidad = st.selectbox(
"Modalidad del programa",
[
"PRESENCIAL",
"DISTANCIA TRADICIONAL",
"DISTANCIA VIRTUAL"
]
)
horas_trabajo = st.selectbox(
"Horas de trabajo semanales",
[
"No trabaja",
"Menos de 10 horas",
"Entre 11 y 20 horas",
"Entre 21 y 30 horas",
"Más de 30 horas"
]
)
genero = st.radio(
"Género",
["F","M"],
horizontal=True
)
estrato = st.slider(
"Estrato socioeconómico",
1,
6,
2
)
with col2:
educ_padre = st.selectbox(
"Educación del padre",
[
"No sabe",
"Ninguno",
"Primaria incompleta",
"Primaria completa",
"Secundaria (Bachillerato) incompleta",
"Secundaria (Bachillerato) completa",
"Técnica o tecnológica incompleta",
"Técnica o tecnológica completa",
"Educación profesional incompleta",
"Educación profesional completa",
"Postgrado"
]
)
educ_madre = st.selectbox(
"Educación de la madre",
[
"No sabe",
"Ninguno",
"Primaria incompleta",
"Primaria completa",
"Secundaria (Bachillerato) incompleta",
"Secundaria (Bachillerato) completa",
"Técnica o tecnológica incompleta",
"Técnica o tecnológica completa",
"Educación profesional incompleta",
"Educación profesional completa",
"Postgrado"
]
)
internet = st.toggle(
"Cuenta con acceso a Internet",
value=True
)
computador = st.toggle(
"Cuenta con computador",
value=True
)
origen = st.selectbox(
"Tipo de Institución",
[
"OFICIAL MUNICIPAL",
"OFICIAL DEPARTAMENTAL",
"OFICIAL NACIONAL",
"NO OFICIAL - FUNDACIÓN",
"NO OFICIAL - CORPORACIÓN",
"REGIMEN ESPECIAL"
]
)
# ======================================================
# PREPARAR DATOS
# ======================================================
estrato_texto = f"Estrato {estrato}"
internet_texto = "Si" if internet else "No"
computador_texto = "Si" if computador else "No"
# ======================================================
# BOTÓN PREDICCIÓN
# ======================================================
if st.button("🔍 Realizar predicción"):
entrada = pd.DataFrame({
"PERIODO":[periodo],
"ESTU_METODO_PRGM":[modalidad],
"ESTU_HORASSEMANATRABAJA":[horas_trabajo],
"ESTU_GENERO":[genero],
"FAMI_EDUCACIONPADRE":[educ_padre],
"FAMI_ESTRATOVIVIENDA":[estrato_texto],
"FAMI_TIENECOMPUTADOR":[computador_texto],
"FAMI_TIENEINTERNET":[internet_texto],
"FAMI_EDUCACIONMADRE":[educ_madre],
"INST_ORIGEN":[origen]
})
pred = modelo.predict(entrada)[0]
prob = modelo.predict_proba(entrada)[0][1]
st.divider()
st.subheader("Resultado")
st.metric(
label="Probabilidad de Riesgo",
value=f"{prob*100:.2f}%"
)
if pred == 1:
st.error(
"⚠️ ESTUDIANTE CON RIESGO DE BAJO DESEMPEÑO"
)
st.markdown("""
El modelo identifica características asociadas con estudiantes
que históricamente han presentado bajo desempeño en razonamiento cuantitativo.
""")
else:
st.success(
"✅ ESTUDIANTE SIN RIESGO DE BAJO DESEMPEÑO"
)
st.markdown("""
El estudiante presenta características asociadas
con desempeño esperado según los patrones aprendidos por el modelo.
""")
# ======================================================
# PIE DE PÁGINA
# ======================================================
st.divider()
st.caption(
"Developed by Daniel Felipe Lezcano Ríos | "
"Maestría en Ciencia de Datos - Universidad Pontificia Bolivariana (UPB)"
)